### ISSUE TITLE
Software dev is easy and for kids, and has absolutely nothing to do with a real and serious complex subject like engineering. 

### ISSUE THREAD

**Issue by ghost** [sam4k/linux-kernel-resources#2]
This post is realted to a false and disrespectful statement you made in your anti-cheat/gaming related blog post.

Sam @sam4k , Engineering has nothing to do with sitting behind a keyboard and writing code. There is no such thing as "reverse" "engineering". Engineering is a real subject. Engineering means designing and building real mechanical systems, like vehicular engines and turbojets. Software devs are claiming the most ridiculous of false claims these days. Software dev is easy and for kids, and has absolutely nothing to do with a real and serious complex subject like engineering. 

Stop being disrespectful to Engineering. And stop these stupid lies.

**Comment by 0xmachos** [comment]
Fuck up mate, your maw wears a denim trackie
